name: node docker build & push

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  generate-jobs:
    name: node-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            name: node-14-alpine3.15
            image: dongjiang1989/alpine
            file: ./node/14/alpine3.15/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-14-alpine3.16
            image: dongjiang1989/alpine
            file: ./node/14/alpine3.16/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-14-bullseye
            image: dongjiang1989/bullseye
            file: ./node/14/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-14-buster
            image: dongjiang1989/buster
            file: ./node/14/buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-14-slim-bullseye
            image: dongjiang1989/bullseye-slim
            file: ./node/14/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-14-slim-buster
            image: dongjiang1989/buster-slim
            file: ./node/14/slim-buster/Dockerfile
            platforms: linux/amd64,linux/arm64
            
          -
            name: node-16-alpine3.15
            image: dongjiang1989/alpine
            file: ./node/16/alpine3.15/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-16-alpine3.16
            image: dongjiang1989/alpine
            file: ./node/16/alpine3.16/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-16-bullseye
            image: dongjiang1989/bullseye
            file: ./node/16/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-16-buster
            image: dongjiang1989/buster
            file: ./node/16/buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-16-slim-bullseye
            image: dongjiang1989/bullseye-slim
            file: ./node/16/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-16-slim-buster
            image: dongjiang1989/buster-slim
            file: ./node/16/slim-buster/Dockerfile
            platforms: linux/amd64,linux/arm64

          -
            name: node-18-alpine3.15
            image: dongjiang1989/alpine
            file: ./node/18/alpine3.15/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-18-alpine3.16
            image: dongjiang1989/alpine
            file: ./node/18/alpine3.16/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-18-bullseye
            image: dongjiang1989/bullseye
            file: ./node/18/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-18-buster
            image: dongjiang1989/buster
            file: ./node/18/buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-18-slim-bullseye
            image: dongjiang1989/bullseye-slim
            file: ./node/18/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-18-slim-buster
            image: dongjiang1989/buster-slim
            file: ./node/18/slim-buster/Dockerfile
            platforms: linux/amd64,linux/arm64

          -
            name: node-19-alpine3.15
            image: dongjiang1989/alpine
            file: ./node/19/alpine3.15/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-19-alpine3.16
            image: dongjiang1989/alpine
            file: ./node/19/alpine3.16/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-19-bullseye
            image: dongjiang1989/bullseye
            file: ./node/19/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-19-buster
            image: dongjiang1989/buster
            file: ./node/19/buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-19-slim-bullseye
            image: dongjiang1989/bullseye-slim
            file: ./node/19/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: node-19-slim-buster
            image: dongjiang1989/buster-slim
            file: ./node/19/slim-buster/Dockerfile
            platforms: linux/amd64,linux/arm64

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.image }}:${{ matrix.name }}
      - name: Test ${{ matrix.name }}
        run: |
          docker pull ${{ matrix.image}}:${{ matrix.name }}
          docker image inspect ${{ matrix.image}}:${{ matrix.name }}
