name: ruby docker build & push

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  generate-jobs:
    name: ruby-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            name: ruby-2.7.6-alpine3.15
            image: dongjiang1989/alpine
            file: ./ruby/2.7/alpine3.15/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-2.7.6-alpine3.16
            image: dongjiang1989/alpine
            file: ./ruby/2.7/alpine3.16/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-2.7.6-bullseye
            image: dongjiang1989/bullseye
            file: ./ruby/2.7/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-2.7.6-buster
            image: dongjiang1989/buster
            file: ./ruby/2.7/buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-2.7.6-slim-bullseye
            image: dongjiang1989/bullseye-slim
            file: ./ruby/2.7/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-2.7.6-slim-buster
            image: dongjiang1989/buster-slim
            file: ./ruby/2.7/slim-buster/Dockerfile
            platforms: linux/amd64,linux/arm64
            
          -
            name: ruby-3.0.4-alpine3.15
            image: dongjiang1989/alpine
            file: ./ruby/3.0/alpine3.15/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-3.0.4-alpine3.16
            image: dongjiang1989/alpine
            file: ./ruby/3.0/alpine3.16/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-3.0.4-bullseye
            image: dongjiang1989/bullseye
            file: ./ruby/3.0/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-3.0.4-buster
            image: dongjiang1989/buster
            file: ./ruby/3.0/buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-3.0.4-slim-bullseye
            image: dongjiang1989/bullseye-slim
            file: ./ruby/3.0/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-3.0.4-slim-buster
            image: dongjiang1989/buster-slim
            file: ./ruby/3.0/slim-buster/Dockerfile
            platforms: linux/amd64,linux/arm64

          -
            name: ruby-3.1.2-alpine3.15
            image: dongjiang1989/alpine
            file: ./ruby/3.1/alpine3.15/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-3.1.2-alpine3.16
            image: dongjiang1989/alpine
            file: ./ruby/3.1/alpine3.16/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-3.1.2-bullseye
            image: dongjiang1989/bullseye
            file: ./ruby/3.1/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-3.1.2-buster
            image: dongjiang1989/buster
            file: ./ruby/3.1/buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-3.1.2-slim-bullseye
            image: dongjiang1989/bullseye-slim
            file: ./ruby/3.1/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby-3.1.2-slim-buster
            image: dongjiang1989/buster-slim
            file: ./ruby/3.1/slim-buster/Dockerfile
            platforms: linux/amd64,linux/arm64

          -
            name: 3.2.0-preview3-alpine3.15
            image: dongjiang1989/alpine
            file: ./ruby/3.2-rc/alpine3.15/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby/3.3.2.0-preview3-alpine3.16
            image: dongjiang1989/alpine
            file: ./ruby/3.2-rc/alpine3.16/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby/3.3.2.0-preview3-bullseye
            image: dongjiang1989/bullseye
            file: ./ruby/3.2-rc/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby/3.3.2.0-preview3-buster
            image: dongjiang1989/buster
            file: ./ruby/3.2-rc/buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby/3.3.2.0-preview3-slim-bullseye
            image: dongjiang1989/bullseye-slim
            file: ./ruby/3.2-rc/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: ruby/3.3.2.0-preview3-slim-buster
            image: dongjiang1989/buster-slim
            file: ./ruby/3.2-rc/slim-buster/Dockerfile
            platforms: linux/amd64,linux/arm64

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.image }}:${{ matrix.name }}
      - name: Test ${{ matrix.name }}
        run: |
          docker pull ${{ matrix.image}}:${{ matrix.name }}
          docker image inspect ${{ matrix.image}}:${{ matrix.name }}
